### ISSUE TITLE
can't make it work behind proxy

### ISSUE THREAD

**Issue by tcharos** [further-reading/scraping-browser#25] opened 2023-02-16 07:25 UTC
missing proxy configuration

**Comment by further-reading** [comment] 2023-02-16 08:32
This would be considered a duplicate of "headers writing" I expect. For anything more advanced than simply visiting the url in a standard browser you're best off making the requests in a scrapy shell and using the "load_selector" method on the response.

**Closed as completed by further-reading** 2023-02-16 08:32 UTC
